from tkinter import *
m=Tk()
m.title("NUMBER GUESSING GAME")
lable=Label(m,text="CodeSpeedy")
lable.pack()
frame=Frame(m,width=1200,height=700)
button1=Button(frame,text="enter")
button2=Button(frame,text="number 1")
button3=Button(frame,text="number 2")
button4=Button(frame,text="number 3")
button4.pack(side=LEFT)
button3.pack(side=LEFT)
button2.pack(side=LEFT)
button1.pack(side=LEFT)
frame.pack()
bottomframe=Frame(m,width=1200,height=700)
lable2=Label(bottomframe,text="ASHOKA")
button5=Button(bottomframe,text="Exit")
button5.pack(side=RIGHT)
bottomframe.pack(side=BOTTOM)
mainloop()